#!/bin/bash
docker build --target ughub --tag ug4docker/ughub .
docker build --target $IMAGE_NAME --build-arg UG4_CONF_APTMODULES_UGBUILD="${UG4_CONF_APTMODULES_UGBUILD}" --build-arg UG4DOCKER_CC="$UG4DOCKER_CC" --build-arg UG4DOCKER_CXX="$UG4DOCKER_CXX" .
